# suppress inspection "UnusedProperty" for whole file

# words api configuration
wordsapi.host.name = wordsapi
wordsapi.host.url = wordsapiv1.p.rapidapi.com
wordsapi.host.key = 82e3b94b58mshacb274c2fc786f6p10645fjsnc8e4b5ac12a4
