spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          jdbc:
            lob:
              non_contextual_creation: true
    datasource:
      url: jdbc:postgresql://localhost:5432/thema
      username: thema
      password: thema
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  application:
    name: Thema Application
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    active: development
logging:
  level:
    root: info
    org.springframework.web: info
    org.hibernate: info
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
server:
  port: 8081
  compression:
    enabled: true
  http2:
    enabled: true
  tomcat:
    accesslog:
      enabled: true
      pattern: '%h %l %u %t "%r" %s %b "%{Referer}i" "%{User-Agent}i"'
