spring.jpa.open-in-view=true
spring.application.name = Thema Application

# log configuration
logging.level.root=info
logging.level.org.springframework.web=debug
logging.level.org.hibernate=error
spring.output.ansi.enabled=ALWAYS

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect