version: '3'

# Define services
services:

  # PostgreSQL Database for the application
  thema-postgres:
    image: "postgres:10.4-alpine"
    restart: always
    container_name: thema-postgres
    # Mount a volume for persistent data storage
    volumes:
      - thema-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    # Set environment variables for the database
    environment:
      POSTGRES_DB: thema
      POSTGRES_USER: thema
      POSTGRES_PASSWORD: thema

  # Back-end Spring Boot Application
  thema-app:
    # Build the Docker image from the Dockerfile in the thema-app directory
    build: ./thema-app
    container_name: thema-app
    # Set environment variables for the Spring Boot application
    environment:
      DB_SERVER: thema-postgres
      POSTGRES_DB: thema
      POSTGRES_USER: thema
      POSTGRES_PASSWORD: thema
    ports:
      - '8080:8080'
    # Connect to the thema-postgres container
    depends_on:
      - thema-postgres

  # Front-end Angular Application
  thema-front:
    # Build the Docker image from the Dockerfile in the thema-front directory
    build: ./thema-front
    container_name: thema-front
    ports:
      - '4200:80'
    # Connect to the thema-app container
    depends_on:
      - thema-app

# Define volumes for persistent data storage
volumes:
  thema-data:
